import type { Bike } from "./types";

// Sample inventory. Specs are typical for these models but every figure here is
// illustrative and should be replaced by the shop's own inspection data.
export const SEED_BIKES: Bike[] = [
  {
    id: "b001",
    slug: "rad-power-radcity-5-plus-2023",
    brand: "Rad Power Bikes",
    model: "RadCity 5 Plus",
    year: 2023,
    price: 1149,
    miles: 640,
    category: "Commuter",
    frameSize: "L",
    condition: "Very good",
    batteryWh: 672,
    batteryHealth: 94,
    rangeMiles: 38,
    motor: "750W rear hub",
    topAssistMph: 20,
    color: "Charcoal",
    status: "available",
    photoCount: 5,
    summary: "One-owner commuter with a fresh chain and new brake pads. Light scuff on the left crank arm, nothing structural.",
    inspection: ["Battery load-tested at 94% of rated capacity", "New chain and brake pads fitted", "Hydraulic brakes bled", "Wheels trued, spokes tensioned", "Firmware current"],
    included: ["Charger", "Rear rack", "Fenders", "Two keys"],
    hue: 152,
    addedAt: "2026-08-28",
  },
  {
    id: "b002",
    slug: "aventon-level-2-2024",
    brand: "Aventon",
    model: "Level.2",
    year: 2024,
    price: 1299,
    miles: 210,
    category: "Commuter",
    frameSize: "M",
    condition: "Excellent",
    batteryWh: 672,
    batteryHealth: 98,
    rangeMiles: 42,
    motor: "500W rear hub, torque sensor",
    topAssistMph: 28,
    color: "Clay",
    status: "available",
    photoCount: 6,
    summary: "Barely ridden, still on the original tires. Torque sensor makes this the most natural-feeling hub bike in the shop right now.",
    inspection: ["Battery load-tested at 98%", "Original tires, plenty of tread", "Brakes and shifting adjusted", "No frame damage"],
    included: ["Charger", "Fenders", "Rear rack", "Owner's manual"],
    hue: 24,
    addedAt: "2026-09-02",
  },
  {
    id: "b003",
    slug: "trek-allant-plus-7-2022",
    brand: "Trek",
    model: "Allant+ 7",
    year: 2022,
    price: 2450,
    miles: 1820,
    category: "Commuter",
    frameSize: "L",
    condition: "Good",
    batteryWh: 625,
    batteryHealth: 89,
    rangeMiles: 45,
    motor: "Bosch Performance Line CX mid-drive",
    topAssistMph: 28,
    color: "Dark Aquatic",
    status: "available",
    photoCount: 6,
    summary: "Well-used daily commuter with a Bosch mid-drive that still pulls hard. Cosmetic wear on the top tube and saddle, drivetrain replaced by us.",
    inspection: ["Battery load-tested at 89%", "New cassette and chain", "Bosch diagnostic run, no fault codes", "Front light replaced"],
    included: ["Charger", "Integrated lights", "Rear rack", "Kickstand"],
    hue: 200,
    addedAt: "2026-08-19",
  },
  {
    id: "b004",
    slug: "specialized-turbo-vado-4-2023",
    brand: "Specialized",
    model: "Turbo Vado 4.0",
    year: 2023,
    price: 2895,
    miles: 930,
    category: "Commuter",
    frameSize: "M",
    condition: "Very good",
    batteryWh: 710,
    batteryHealth: 95,
    rangeMiles: 55,
    motor: "Specialized 2.0 mid-drive",
    topAssistMph: 28,
    color: "Cast Black",
    status: "reserved",
    photoCount: 5,
    summary: "Quiet mid-drive, suspension fork, and the big 710Wh battery. Currently on hold for a customer, ask to be next in line.",
    inspection: ["Battery load-tested at 95%", "Fork serviced", "Tubeless tires re-sealed", "Mission Control app paired and tested"],
    included: ["Charger", "Integrated lights", "Fenders", "Rear rack"],
    hue: 260,
    addedAt: "2026-08-25",
  },
  {
    id: "b005",
    slug: "tern-gsd-s10-2022",
    brand: "Tern",
    model: "GSD S10",
    year: 2022,
    price: 3400,
    miles: 2400,
    category: "Cargo",
    frameSize: "M",
    riderFit: "4'11\" to 6'5\"",
    condition: "Good",
    batteryWh: 500,
    batteryHealth: 86,
    rangeMiles: 30,
    motor: "Bosch Cargo Line mid-drive",
    topAssistMph: 20,
    color: "Beetle Blue",
    status: "available",
    photoCount: 7,
    summary: "Family hauler that has done real hauling. One-size frame fits riders from about 4'11\" to 6'5\". Comes with the Clubhouse rails and two child seats.",
    inspection: ["Battery load-tested at 86%", "Rear brake rotor replaced", "Cargo rails checked and torqued", "Second battery mount present, second battery not included"],
    included: ["Charger", "Clubhouse rails", "Two Thule Yepp child seats", "Integrated lights", "Dual kickstand"],
    hue: 215,
    addedAt: "2026-08-10",
  },
  {
    id: "b006",
    slug: "rad-power-radwagon-4-2022",
    brand: "Rad Power Bikes",
    model: "RadWagon 4",
    year: 2022,
    price: 1099,
    miles: 1150,
    category: "Cargo",
    frameSize: "M",
    condition: "Good",
    batteryWh: 672,
    batteryHealth: 90,
    rangeMiles: 32,
    motor: "750W rear hub",
    topAssistMph: 20,
    color: "Orange",
    status: "available",
    photoCount: 5,
    summary: "Budget cargo bike for school runs and grocery trips. Some paint chips on the rear deck from use, everything else tight.",
    inspection: ["Battery load-tested at 90%", "New tires, the originals were recalled", "Brakes adjusted", "Deck bolts torqued"],
    included: ["Charger", "Running boards", "Deck pad", "Front rack"],
    hue: 30,
    addedAt: "2026-08-30",
  },
  {
    id: "b007",
    slug: "lectric-xp-3-2023",
    brand: "Lectric",
    model: "XP 3.0",
    year: 2023,
    price: 749,
    miles: 480,
    category: "Folding",
    frameSize: "S",
    condition: "Very good",
    batteryWh: 500,
    batteryHealth: 93,
    rangeMiles: 28,
    motor: "500W rear hub",
    topAssistMph: 20,
    color: "Black",
    status: "available",
    photoCount: 4,
    summary: "Folds in about ten seconds and fits in a hatchback. Step-through frame, good for shorter riders and for keeping in an apartment.",
    inspection: ["Battery load-tested at 93%", "Folding latches inspected", "Brakes adjusted", "Tire pressure and sealant checked"],
    included: ["Charger", "Rear rack", "Fenders", "Front light"],
    hue: 0,
    addedAt: "2026-09-04",
  },
  {
    id: "b008",
    slug: "brompton-electric-c-line-2021",
    brand: "Brompton",
    model: "Electric C Line",
    year: 2021,
    price: 2250,
    miles: 1300,
    category: "Folding",
    frameSize: "M",
    condition: "Very good",
    batteryWh: 300,
    batteryHealth: 88,
    rangeMiles: 22,
    motor: "250W front hub",
    topAssistMph: 15,
    color: "Turkish Green",
    status: "available",
    photoCount: 6,
    summary: "The train-and-office bike. Tiny fold, front bag battery you carry inside. Range is short by design, the trade-off is the size.",
    inspection: ["Battery load-tested at 88%", "Hinge clamps adjusted", "Chain and sprockets replaced", "Front bag zip repaired"],
    included: ["Charger", "Battery bag", "Folding pedals", "Front carrier block"],
    hue: 165,
    addedAt: "2026-08-14",
  },
  {
    id: "b009",
    slug: "specialized-turbo-levo-comp-2022",
    brand: "Specialized",
    model: "Turbo Levo Comp",
    year: 2022,
    price: 3950,
    miles: 1600,
    category: "Mountain",
    frameSize: "L",
    condition: "Good",
    batteryWh: 700,
    batteryHealth: 91,
    rangeMiles: 35,
    motor: "Specialized 2.2 mid-drive",
    topAssistMph: 20,
    color: "Smoke",
    status: "available",
    photoCount: 7,
    summary: "Full-suspension trail bike that has seen Patapsco regularly. Suspension freshly serviced, new tires, rock rash on the downtube guard only.",
    inspection: ["Battery load-tested at 91%", "Fork and shock serviced", "New tires front and rear", "Pivot bearings checked, no play", "Brake pads at 70%"],
    included: ["Charger", "SWAT tool", "Spare derailleur hanger"],
    hue: 90,
    addedAt: "2026-08-22",
  },
  {
    id: "b010",
    slug: "giant-trance-x-e-plus-2-2023",
    brand: "Giant",
    model: "Trance X E+ 2",
    year: 2023,
    price: 3600,
    miles: 700,
    category: "Mountain",
    frameSize: "XL",
    condition: "Excellent",
    batteryWh: 625,
    batteryHealth: 96,
    rangeMiles: 38,
    motor: "Yamaha SyncDrive Pro mid-drive",
    topAssistMph: 20,
    color: "Sage",
    status: "available",
    photoCount: 6,
    summary: "Big frame for tall riders, low miles, original owner sized down. Hard to find an XL used, so this one will not sit long.",
    inspection: ["Battery load-tested at 96%", "Suspension checked, no service needed yet", "Drivetrain at 80%", "No frame damage"],
    included: ["Charger", "Owner's manual"],
    hue: 120,
    addedAt: "2026-09-05",
  },
  {
    id: "b011",
    slug: "cannondale-topstone-neo-sl-2-2022",
    brand: "Cannondale",
    model: "Topstone Neo SL 2",
    year: 2022,
    price: 1850,
    miles: 2100,
    category: "Road",
    frameSize: "M",
    condition: "Good",
    batteryWh: 250,
    batteryHealth: 85,
    rangeMiles: 30,
    motor: "Mahle X35 rear hub",
    topAssistMph: 20,
    color: "Chalk",
    status: "available",
    photoCount: 5,
    summary: "Gravel bike with a hidden hub motor. Rides like a normal drop-bar bike until you hit a hill. Battery is the original and shows it.",
    inspection: ["Battery load-tested at 85%", "New bar tape", "Chain replaced", "Headset adjusted"],
    included: ["Charger", "Bottle cages"],
    hue: 45,
    addedAt: "2026-08-05",
  },
  {
    id: "b012",
    slug: "ride1up-roadster-v2-2023",
    brand: "Ride1Up",
    model: "Roadster V2",
    year: 2023,
    price: 699,
    miles: 900,
    category: "Road",
    frameSize: "L",
    condition: "Fair",
    batteryWh: 252,
    batteryHealth: 82,
    rangeMiles: 20,
    motor: "350W rear hub, belt drive",
    topAssistMph: 24,
    color: "Gloss Black",
    status: "sold",
    photoCount: 4,
    summary: "Light single-speed belt-drive city bike. Sold, kept here so the listing history stays honest for a few weeks.",
    inspection: ["Battery load-tested at 82%", "Belt tension set", "Rear brake cable replaced"],
    included: ["Charger"],
    hue: 330,
    addedAt: "2026-07-20",
  },
];

export const getBike = (slug: string, list: Bike[] = SEED_BIKES) => list.find((b) => b.slug === slug);

export const availableBikes = (list: Bike[] = SEED_BIKES) => list.filter((b) => b.status !== "sold");

export const relatedBikes = (bike: Bike, list: Bike[] = SEED_BIKES, n = 3) =>
  list
    .filter((b) => b.slug !== bike.slug && b.status !== "sold")
    .sort((a, b) => {
      const score = (x: Bike) => (x.category === bike.category ? 2 : 0) + (x.frameSize === bike.frameSize ? 1 : 0);
      return score(b) - score(a) || Math.abs(a.price - bike.price) - Math.abs(b.price - bike.price);
    })
    .slice(0, n);
