import type { Bike } from "./types";
import { PHOTOS as P } from "./photos";

// Sample inventory. Photos are Unsplash stock chosen to match each listing's
// type and color; they are not photos of the exact models named, and every
// figure here is illustrative. A real shop would replace all of it with its
// own inspection data and photos.
export const SEED_BIKES: Bike[] = [
  {
    id: "b001",
    slug: "kbo-breeze-2023",
    brand: "KBO",
    model: "Breeze",
    year: 2023,
    price: 899,
    miles: 640,
    category: "Commuter",
    frameSize: "L",
    condition: "Very good",
    batteryWh: 768,
    batteryHealth: 94,
    rangeMiles: 40,
    motor: "500W rear hub",
    topAssistMph: 22,
    color: "White",
    status: "available",
    photos: [P.kboRiding, P.kboBattery],
    summary: "One-owner commuter with a fresh chain and new brake pads. Light scuff on the left crank arm, nothing structural.",
    inspection: ["Battery load-tested at 94% of rated capacity", "New chain and brake pads fitted", "Wheels trued, spokes tensioned", "Firmware current"],
    included: ["Charger", "Rear rack", "Fenders", "Two keys"],
    hue: 152,
    addedAt: "2026-08-28",
  },
  {
    id: "b002",
    slug: "kbo-breeze-step-thru-2024",
    brand: "KBO",
    model: "Breeze Step-Thru",
    year: 2024,
    price: 949,
    miles: 210,
    category: "Commuter",
    frameSize: "M",
    condition: "Excellent",
    batteryWh: 768,
    batteryHealth: 98,
    rangeMiles: 42,
    motor: "500W rear hub",
    topAssistMph: 22,
    color: "Sky blue",
    status: "available",
    photos: [P.stepThruSea, P.stepThruStanding, P.stepThruBench],
    summary: "Barely ridden, still on the original tires. Low step-over makes this the easiest bike in the shop to get on and off with a load.",
    inspection: ["Battery load-tested at 98%", "Original tires, plenty of tread", "Brakes and shifting adjusted", "No frame damage"],
    included: ["Charger", "Fenders", "Rear rack", "Owner's manual"],
    hue: 200,
    addedAt: "2026-09-02",
  },
  {
    id: "b003",
    slug: "velotric-discover-1-2023",
    brand: "Velotric",
    model: "Discover 1",
    year: 2023,
    price: 1099,
    miles: 930,
    category: "Commuter",
    frameSize: "M",
    condition: "Very good",
    batteryWh: 692,
    batteryHealth: 93,
    rangeMiles: 45,
    motor: "500W rear hub",
    topAssistMph: 20,
    color: "Teal",
    status: "available",
    photos: [P.tealStepThru],
    summary: "Comfortable upright commuter with a suspension fork and hydraulic brakes. Saddle replaced with a wider one by the previous owner, original included.",
    inspection: ["Battery load-tested at 93%", "Fork checked, no play", "Hydraulic brakes bled", "Lights and horn tested"],
    included: ["Charger", "Integrated lights", "Fenders", "Rear rack", "Original saddle"],
    hue: 170,
    addedAt: "2026-08-25",
  },
  {
    id: "b004",
    slug: "vanmoof-s3-2021",
    brand: "VanMoof",
    model: "S3",
    year: 2021,
    price: 1150,
    miles: 1820,
    category: "Commuter",
    frameSize: "L",
    condition: "Good",
    batteryWh: 504,
    batteryHealth: 87,
    rangeMiles: 35,
    motor: "250W front hub, automatic shifting",
    topAssistMph: 20,
    color: "Matte black",
    status: "reserved",
    photos: [P.blackUrban],
    summary: "Clean city bike with the integrated lights and alarm working. Proprietary parts, so we keep a small stock of spares and say so up front. On hold for a customer, ask to be next in line.",
    inspection: ["Battery load-tested at 87%", "Automatic shifting recalibrated", "App pairing tested", "New chain"],
    included: ["Charger", "Integrated lights", "Kick lock and app", "Owner's manual"],
    hue: 260,
    addedAt: "2026-08-19",
  },
  {
    id: "b005",
    slug: "ride1up-700-series-2022",
    brand: "Ride1Up",
    model: "700 Series",
    year: 2022,
    price: 799,
    miles: 2400,
    category: "Commuter",
    frameSize: "L",
    condition: "Fair",
    batteryWh: 720,
    batteryHealth: 82,
    rangeMiles: 30,
    motor: "750W rear hub",
    topAssistMph: 28,
    color: "Black",
    status: "sold",
    photos: [P.darkGravel, P.darkRiding],
    summary: "High-mileage commuter that was ridden daily. Sold, kept here so the listing history stays honest for a few weeks.",
    inspection: ["Battery load-tested at 82%", "Rear brake cable replaced", "Cassette and chain replaced"],
    included: ["Charger", "Rear rack"],
    hue: 30,
    addedAt: "2026-07-20",
  },
  {
    id: "b006",
    slug: "babboe-city-e-2022",
    brand: "Babboe",
    model: "City-E",
    year: 2022,
    price: 2250,
    miles: 1150,
    category: "Cargo",
    frameSize: "M",
    riderFit: "5'0\" to 6'3\"",
    condition: "Good",
    batteryWh: 450,
    batteryHealth: 88,
    rangeMiles: 28,
    motor: "250W front hub",
    topAssistMph: 15,
    color: "Orange box, black frame",
    status: "available",
    photos: [P.orangeBox],
    summary: "Two-wheel front loader for school runs and grocery trips. Box seats two kids with belts. Some paint chips on the box edge from use, everything else tight.",
    inspection: ["Battery load-tested at 88%", "Steering linkage checked and greased", "Box mounts torqued", "New tires"],
    included: ["Charger", "Bench seat and two belts", "Rain cover", "Double kickstand"],
    hue: 30,
    addedAt: "2026-08-30",
  },
  {
    id: "b007",
    slug: "babboe-city-mountain-2021",
    brand: "Babboe",
    model: "City Mountain",
    year: 2021,
    price: 2650,
    miles: 2400,
    category: "Cargo",
    frameSize: "M",
    riderFit: "5'2\" to 6'4\"",
    condition: "Good",
    batteryWh: 500,
    batteryHealth: 86,
    rangeMiles: 30,
    motor: "Yamaha PW mid-drive",
    topAssistMph: 15,
    color: "Wood box, black frame",
    status: "available",
    photos: [P.brownBox, P.boxDetail],
    summary: "Family hauler that has done real hauling, and the mid-drive version, so it climbs. Box takes two kids or a week of groceries. Comes with the rain tent and two child seats.",
    inspection: ["Battery load-tested at 86%", "Rear brake rotor replaced", "Box bolts checked and torqued", "Yamaha diagnostic run, no fault codes"],
    included: ["Charger", "Rain tent", "Two child seats", "Integrated lights", "Double kickstand"],
    hue: 215,
    addedAt: "2026-08-10",
  },
  {
    id: "b008",
    slug: "lectric-xp-3-2023",
    brand: "Lectric",
    model: "XP 3.0",
    year: 2023,
    price: 749,
    miles: 480,
    category: "Folding",
    frameSize: "S",
    riderFit: "4'11\" to 6'3\"",
    condition: "Very good",
    batteryWh: 500,
    batteryHealth: 93,
    rangeMiles: 28,
    motor: "500W rear hub",
    topAssistMph: 20,
    color: "Black",
    status: "available",
    photos: [P.blackFolding],
    summary: "Folds in about ten seconds and fits in a hatchback. Fat tires soak up Baltimore pavement. Good for keeping in an apartment.",
    inspection: ["Battery load-tested at 93%", "Folding latches inspected", "Brakes adjusted", "Tire pressure and sealant checked"],
    included: ["Charger", "Rear rack", "Fenders", "Front light"],
    hue: 0,
    addedAt: "2026-09-04",
  },
  {
    id: "b009",
    slug: "dahon-unio-e20-2022",
    brand: "Dahon",
    model: "Unio E20",
    year: 2022,
    price: 1350,
    miles: 1300,
    category: "Folding",
    frameSize: "M",
    riderFit: "4'8\" to 6'4\"",
    condition: "Very good",
    batteryWh: 360,
    batteryHealth: 89,
    rangeMiles: 25,
    motor: "250W rear hub",
    topAssistMph: 20,
    color: "Blue and white",
    status: "available",
    photos: [P.blueFolding, P.blueFoldingDetail],
    summary: "The train-and-office bike. Small fold, light enough to carry up a flight of stairs. Range is short by design, the trade-off is the size.",
    inspection: ["Battery load-tested at 89%", "Hinge clamps adjusted", "Chain and sprockets replaced", "Folding pedals checked"],
    included: ["Charger", "Folding pedals", "Fenders", "Carry strap"],
    hue: 165,
    addedAt: "2026-08-14",
  },
  {
    id: "b010",
    slug: "himiway-cruiser-2023",
    brand: "Himiway",
    model: "Cruiser",
    year: 2023,
    price: 1099,
    miles: 700,
    category: "Fat tire",
    frameSize: "L",
    condition: "Excellent",
    batteryWh: 840,
    batteryHealth: 96,
    rangeMiles: 45,
    motor: "750W rear hub",
    topAssistMph: 20,
    color: "Black",
    status: "available",
    photos: [P.blackFat],
    summary: "Big battery, four-inch tires, low miles. The bike for gravel trails, beach paths, and winter commutes. Hard to find one this clean used.",
    inspection: ["Battery load-tested at 96%", "Brake pads at 80%", "Tires checked, no cuts", "No frame damage"],
    included: ["Charger", "Rear rack", "Owner's manual"],
    hue: 90,
    addedAt: "2026-09-05",
  },
  {
    id: "b011",
    slug: "himiway-cruiser-step-thru-2022",
    brand: "Himiway",
    model: "Cruiser Step-Thru",
    year: 2022,
    price: 999,
    miles: 1600,
    category: "Fat tire",
    frameSize: "M",
    condition: "Good",
    batteryWh: 840,
    batteryHealth: 90,
    rangeMiles: 40,
    motor: "750W rear hub",
    topAssistMph: 20,
    color: "White and red",
    status: "available",
    photos: [P.whiteFat],
    summary: "Step-through version of the Cruiser with the same big battery. Ridden on trails regularly, so expect some rock rash on the chainstay.",
    inspection: ["Battery load-tested at 90%", "Front rotor replaced", "New tires front and rear", "Rack bolts torqued"],
    included: ["Charger", "Rear rack", "Fenders"],
    hue: 350,
    addedAt: "2026-08-22",
  },
  {
    id: "b012",
    slug: "specialized-turbo-levo-comp-2022",
    brand: "Specialized",
    model: "Turbo Levo Comp",
    year: 2022,
    price: 3950,
    miles: 1600,
    category: "Mountain",
    frameSize: "L",
    condition: "Good",
    batteryWh: 700,
    batteryHealth: 91,
    rangeMiles: 35,
    motor: "Specialized 2.2 mid-drive",
    topAssistMph: 20,
    color: "Red",
    status: "available",
    photos: [P.redMtb],
    summary: "Full-suspension trail bike that has seen Patapsco regularly. Suspension freshly serviced, new tires, rock rash on the downtube guard only.",
    inspection: ["Battery load-tested at 91%", "Fork and shock serviced", "New tires front and rear", "Pivot bearings checked, no play", "Brake pads at 70%"],
    included: ["Charger", "SWAT tool", "Spare derailleur hanger"],
    hue: 120,
    addedAt: "2026-08-22",
  },
  {
    id: "b013",
    slug: "trek-powerfly-4-2023",
    brand: "Trek",
    model: "Powerfly 4",
    year: 2023,
    price: 2400,
    miles: 900,
    category: "Mountain",
    frameSize: "XL",
    condition: "Very good",
    batteryWh: 625,
    batteryHealth: 95,
    rangeMiles: 38,
    motor: "Bosch Performance Line CX mid-drive",
    topAssistMph: 20,
    color: "Blue",
    status: "available",
    photos: [P.hardtailBags],
    summary: "Hardtail e-MTB set up for overnight trips, bags included. XL frame for tall riders, original owner sized down. Hard to find an XL used, so this one will not sit long.",
    inspection: ["Battery load-tested at 95%", "Fork serviced", "Drivetrain at 80%", "Bosch diagnostic run, no fault codes"],
    included: ["Charger", "Frame bag and handlebar roll", "Owner's manual"],
    hue: 45,
    addedAt: "2026-08-05",
  },
];

export const SEED_SLUGS = new Set(SEED_BIKES.map((b) => b.slug));

/** Detail-page href. Seed bikes have prerendered pages; owner-added bikes use the client-rendered viewer. */
export const bikeHref = (slug: string) => (SEED_SLUGS.has(slug) ? `/bikes/${slug}` : `/bikes/view?slug=${encodeURIComponent(slug)}`);

export const getBike = (slug: string, list: Bike[] = SEED_BIKES) => list.find((b) => b.slug === slug);

export const availableBikes = (list: Bike[] = SEED_BIKES) => list.filter((b) => b.status !== "sold");

export const relatedBikes = (bike: Bike, list: Bike[] = SEED_BIKES, n = 3) =>
  list
    .filter((b) => b.slug !== bike.slug && b.status !== "sold")
    .sort((a, b) => {
      const score = (x: Bike) => (x.category === bike.category ? 2 : 0) + (x.frameSize === bike.frameSize ? 1 : 0);
      return score(b) - score(a) || Math.abs(a.price - bike.price) - Math.abs(b.price - bike.price);
    })
    .slice(0, n);
